name: Generate llms-full.md

on:
  push:
    branches: [main]
    paths:
      - 'llms.md'
      - 'package.json'
      - 'LICENSE'
      - 'docs/llms-full-template.md'
      - 'scripts/generate-llms-full.js'
  pull_request:
    paths:
      - 'llms.md'
      - 'package.json'
      - 'LICENSE'
      - 'docs/llms-full-template.md'
      - 'scripts/generate-llms-full.js'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for git contributors
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Generate llms-full.md
      run: node scripts/generate-llms-full.js
    
    - name: Commit changes if on main branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.ACT != 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: Update llms-full.md from llms.md [skip ci]"
        file_pattern: "llms-full.md examples/llms-full.md"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
        
    - name: Show commit message (for act)
      if: env.ACT == 'true'
      run: |
        echo "When running in GitHub Actions, the following files would be committed:"
        echo "- llms-full.md"
        echo "- examples/llms-full.md"
        echo "Commit message: docs: Update llms-full.md from llms.md [skip ci]"
    
    - name: Show generated files in PR
      if: github.event_name == 'pull_request'
      run: |
        echo "## Generated llms-full.md Files" >> $GITHUB_STEP_SUMMARY
        echo "The following files have been generated:" >> $GITHUB_STEP_SUMMARY
        echo "- llms-full.md" >> $GITHUB_STEP_SUMMARY
        echo "- examples/llms-full.md" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "These files will be automatically committed when merged to main." >> $GITHUB_STEP_SUMMARY