name: Markdown Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions for git-auto-commit-action
permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies using npm
      run: npm install
      
    - name: Fix markdown issues (simple mode)
      run: node scripts/fix-all.js
      if: github.event_name == 'pull_request'
    
    - name: Commit fixes if needed
      uses: stefanzweifel/git-auto-commit-action@v4
      if: github.event_name == 'pull_request'
      with:
        commit_message: "style: Fix markdown formatting"
        file_pattern: "**/*.md"
    
    - name: Run linting
      run: npx markdownlint "**/*.md" --ignore node_modules
    
    - name: Check formatting
      run: npx prettier --check "**/*.md" || echo "Format check failed, continuing anyway"
    
    - name: Validate llms.md
      run: node scripts/validate-llms-md.js